version: '3.8'
services:
db:
image: postgres:15
environment:
POSTGRES_USER: postgres
POSTGRES_PASSWORD: postgres
POSTGRES_DB: payroll
ports:
- "5432:5432"
volumes:
- db-data:/var/lib/postgresql/data
2
volumes:
db-data: